<a href="https://colab.research.google.com/github/Gaddameedi/DSWP_Day2_Practice_Simplilearn/blob/main/Data_3_to_6_Jan_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Science - Data + Science.
Machine learning - Training the machines to take intelligent decision as we are taking. 


Data
- Structured 
- Unstructured
- Semi Structured Data

Science
- Stats - Descriptive stats, Infrential Stats
- Matehmatical models
- Visualization

Data science use cases
1. For any Buisness problem
2. Classification of mail
3. Fraud Detection
4. Recommendation Enginer
5. Auto complete sentence
6. Predictive Analysis
7. Stock price prediction
8. House price prediction
9. Weather Prediction

In [ ]:
Data scientist Lifecycle

1. Collecting Data
2. Understanding buisness problem
3. Data cleaning  (Duplicate data, Wrong Entry, null values, Outliers)
4. Data Exploration (EDA) Explorartory Data Analysis
5. Data Visualization (Bar graph, Histogram, Scatter plot, Line graph, Heatmap)
6. Data Manipulation
7. Scaling, PCA  (Scaling - Min max scaling, StandardScaler)(Principal component analysis)
8. Splitting the data (Training data, Testing data)
9. Training the model
10. Getting prediction from model




In [ ]:
Python
1.Easy to learn
2. Large no. of libraries
3. open source
4. large coummunity


In [ ]:
Library - It is a bundle of function that can call for your use 
by provided some keywords that are specified to these functions. 

1. Numpy - Numerical Python
2. Pandas - Reading writing files, Manipualtion
3. Matplotlib - Data visualization
4. Seaborn -Data visualization
5. Scikit-learn - Machine learning



In [ ]:
#Python
#Adding two numbers
3+2

5

In [ ]:
#Adding  numbers
45*45

2025

In [ ]:
3456-134

3322

In [ ]:
3456/3

1152.0

In [ ]:
2245%21

19

In [ ]:
193 #Integer
'abc' #String
True, False #boolean
193.5 #float


193.5

In [ ]:
a = 5

In [ ]:
type(a)

int

In [ ]:
b =193.5

In [ ]:
type(b)

float

In [ ]:
c = True

In [ ]:
type(c)

bool

In [ ]:
d = 'abc'

In [ ]:
type(d)

str

In [ ]:
a = 45
b =35

In [ ]:
a<=b

False

In [ ]:
a>=b

True

In [ ]:
a==b

False

In [ ]:
a!=b

True

In [ ]:
a =23
b =12
#a = b
a==b

False

Data Structures in Python
1. List
2. Tuple
3. Dict


In [ ]:
#creating a list with 4 different data types
a = [123,23, True, 12.7,123, 'strings',(1,4,5)]

In [ ]:
#Checking type of a variable
type(a)

list

In [ ]:
a

[23, True, [5, 6], 5, 12.7, 123, 'strings']

In [ ]:
#accessing the element from a list
a[1]

23

In [ ]:
# to check total no. of elements in the list
len(a)

9

In [ ]:
b

[True, 12.7, 123, 'strings', (1, 4, 5)]

In [ ]:
#adding an element in the list at last index
a.append(433)

In [ ]:
#inserting an element in list at desired position
a.insert(3,'yjf')

In [ ]:
# Finding the index of a specific element
a.index(433)

11

In [ ]:
#Remove element from list
a.remove(a[0])

In [ ]:
#creating tuples
b = (123, False, 13.7, 'string1',(5,7))

In [ ]:
type(b)

tuple

In [ ]:
b

(123, False, 13.7, 'string1', (5, 7))

In [ ]:
#created the Dictionary
dict = {True:'one',2:'two', 'str':'three'}

In [ ]:
type(dict)

dict

In [ ]:
dict

{True: 'one', 2: 'two', 'str': 'three'}

In [ ]:
#Printing all the keys present in dict
dict.keys()

dict_keys([True, 2, 'str'])

In [ ]:
#Printing all the key values present in dict in the form of tuples
dict.items()

dict_items([(True, 'one'), (2, 'two'), ('str', 'three')])

In [ ]:
#printing all the values of all keys in dict
dict.values()

dict_values(['one', 'two', 'three'])

In [ ]:
#accessing the value of list by giving key name 
dict.get(2)

'two'

In [ ]:
#Adding key value into dict.
dict[4] = 'Four'

In [ ]:
# removing elements from Dict
dict.pop(4)

'Four'

In [ ]:
#removing the key value pair from dict
dict.popitem()

(4, 'Four')

In [ ]:
#syntax to import complete library
import numpy as np

In [ ]:
np.sqrt(125)

11.180339887498949

Numpy - Numerical python 

Array - 1 Darray
      - 2 Darray
      - Multi Darray
      
why we use array
It can mathematical operations
Arrays are fast as compared to list
It has multidimension.
Mutable in nature
More functionality as compared to lists

In [ ]:
#Creating Array
abb = np.array([1,True, 34.5, 'fdg'])

In [ ]:
type(abb)

numpy.ndarray

In [ ]:
#creating a zero array
zero= np.zeros(4)

In [ ]:
#creating all ones array
ones = np.ones(5)

In [ ]:
#creating array by giving no. of elements
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#creating 1 d array by providing start

rew= np.linspace(1,50,10)

In [ ]:
len(rew)

10

In [ ]:
rew.ndim

1

In [ ]:
abc = np.array([4,5,7,9])
dsc = np.array([5,9,8,2])

In [ ]:
abc+dsc

array([ 9, 14, 15, 11])

In [ ]:
ones

array([1., 1., 1., 1., 1.])

In [ ]:
zero

array([0., 0., 0., 0.])

In [ ]:
#creating a 2d array
inn = np.array([[3,5,6,7],[6,7,9,0]])

In [ ]:
type(inn)

numpy.ndarray

In [ ]:
len(inn)

2

In [ ]:
inn.ndim

2

In [ ]:
ret.shape

(6, 2)

In [ ]:
ret = np.array([4,6,8,9,7,5,4,0,6,2,34,65])

In [ ]:
#Converting 1d array to 2 d array
ret = ret.reshape(4,3)

array([[ 4,  6,  8],
       [ 9,  7,  5],
       [ 4,  0,  6],
       [ 2, 34, 65]])

In [ ]:
#Converting 1d array to 2 d array
ret.resize(3,4)

In [ ]:
ret

array([[ 4,  6,  8,  9],
       [ 7,  5,  4,  0],
       [ 6,  2, 34, 65]])

In [ ]:
#splitting array to given parts
array1, array2,array3,array4 = np.hsplit(ret, 4)

In [ ]:
#creating 3d array
wer = np.array([[[3,5,7],[5,8,7]],[[5,7,8],[6,9,0]]])

In [ ]:
wer.shape

(2, 2, 3)

In [ ]:
wer

array([[[3, 5, 7],
        [5, 8, 7]],

       [[5, 7, 8],
        [6, 9, 0]]])

In [ ]:
bed = np.array([3,5,8,7,9,6,8,5,4,3,7,9])

In [ ]:
len(bed)

12

In [ ]:
bed.resize(3,4)

In [ ]:
bed

array([[3, 5, 8, 7],
       [9, 6, 8, 5],
       [4, 3, 7, 9]])

In [ ]:
bed.shape

(2, 3, 2)

In [ ]:
#accessing elements of 1 d array
bed[1][3]

5

In [ ]:
#accessing 2
bed[1:3,1:3]

array([[6, 8],
       [3, 7]])