In [1]:
import numpy as np
arr1 = np.array([33,55,66])
print(arr1)

[33 55 66]


In [2]:
type(arr1)

numpy.ndarray

In [3]:
arr1[1]

55

In [4]:
arr1[1] = 77

In [5]:
arr1

array([33, 77, 66])

In [6]:
arr2 = np.array([[10,20,30,40],[50,60,70,80]])

In [7]:
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [8]:
arr2[0]

array([10, 20, 30, 40])

In [9]:
arr2[0][1]

20

In [10]:
arr2[0][1]=15

In [11]:
arr2

array([[10, 15, 30, 40],
       [50, 60, 70, 80]])

In [12]:
an_array = np.zeros([2,2])

In [13]:
an_array

array([[0., 0.],
       [0., 0.]])

In [14]:
an_array1 = np.ones([2,2])

In [15]:
an_array1

array([[1., 1.],
       [1., 1.]])

In [16]:
an_array2=np.eye(3,3)

In [17]:
an_array2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
an_array3 = np.full([2,2],9)

In [19]:
an_array3

array([[9, 9],
       [9, 9]])

In [20]:
arr3 = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])
arr3

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [21]:
arr3[1:3]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

In [22]:
arr3[1:]

array([[15, 16, 17, 18],
       [19, 20, 21, 22]])

In [23]:
arr3[:,2]

array([13, 17, 21])

In [24]:
arr3[2:,]

array([[19, 20, 21, 22]])

In [26]:
arr4=np.array([[11,12],[15,16],[13,14]])

In [27]:
arr4

array([[11, 12],
       [15, 16],
       [13, 14]])

In [28]:
filter1=(arr4>14)

In [29]:
filter1

array([[False, False],
       [ True,  True],
       [False, False]])

In [30]:
arr4[filter1]

array([15, 16])

In [31]:
filter2=(arr4%2==0)
filter2

array([[False,  True],
       [False,  True],
       [False,  True]])

In [32]:
arr4[filter2]

array([12, 16, 14])

In [34]:
arr5=np.array([12,13],dtype=np.float64)
arr5

array([12., 13.])

In [35]:
arr6=np.array([12.5,13.5],dtype=np.int64)
arr6

array([12, 13], dtype=int64)

In [36]:
x=np.array([[30,40,50],[60,70,80]])
y=np.array([[10,20,100],[15,16,17]])

In [37]:
z=x+y
z

array([[ 40,  60, 150],
       [ 75,  86,  97]])

In [38]:
z=np.add(x,y)
z

array([[ 40,  60, 150],
       [ 75,  86,  97]])

In [39]:
z1=np.subtract(x,y)
z1

array([[ 20,  20, -50],
       [ 45,  54,  63]])

In [40]:
z2=np.multiply(x,y)
z2

array([[ 300,  800, 5000],
       [ 900, 1120, 1360]])

In [41]:
z3=np.divide(x,y)
z3

array([[3.        , 2.        , 0.5       ],
       [4.        , 4.375     , 4.70588235]])

In [42]:
x1=np.array(["xx","yy","zz"])
x2=np.array(["xx","yy","zz","ll"])

In [43]:
np.intersect1d(x1,x2)

array(['xx', 'yy', 'zz'], dtype='<U2')

In [44]:
np.setdiff1d(x1,x2)

array([], dtype='<U2')

In [45]:
np.union1d(x1,x2)

array(['ll', 'xx', 'yy', 'zz'], dtype='<U2')

In [46]:
arr=10*np.random.randn(2,5)
arr

array([[-13.53806458,  -3.26100263,   2.608303  ,   1.669191  ,
          3.85244407],
       [ -9.65229717, -12.10302259,  -7.87239287,  -2.50483561,
          3.50107928]])

In [47]:
arr.mean(axis=0) #columnwise mean

array([-11.59518088,  -7.68201261,  -2.63204493,  -0.41782231,
         3.67676168])

In [48]:
arr.mean(axis=1) #rowwise mean

array([-1.73382583, -5.72629379])

In [49]:
arr.mean()

-3.7300598112140397

In [50]:
import pandas as pd
ser1=pd.Series([100,200,300,400],["xx","yy","zz","ll"])

In [53]:
ser1

xx    100
yy    200
zz    300
ll    400
dtype: int64

In [54]:
ser1['xx']

100

In [55]:
ser1["xx"]=150

In [58]:
ser1

xx    150
yy    200
zz    300
ll    400
dtype: int64

In [59]:
ser1[0]

150

In [60]:
ser1.loc["xx"]

150

In [61]:
ser1.iloc[1]

200

In [63]:
d={'one':pd.Series([100,200,300],index=['apple','ball','clock']),
   'two':pd.Series([111,222,333,444],index=['apple','ball','cerill','dancy'])}
d

{'one': apple    100
 ball     200
 clock    300
 dtype: int64,
 'two': apple     111
 ball      222
 cerill    333
 dancy     444
 dtype: int64}

In [64]:
df=pd.DataFrame(d)

In [65]:
df

one    two
apple   100.0  111.0
ball    200.0  222.0
cerill    NaN  333.0
clock   300.0    NaN
dancy     NaN  444.0

In [66]:
df['one']

apple     100.0
ball      200.0
cerill      NaN
clock     300.0
dancy       NaN
Name: one, dtype: float64

In [67]:
df['one']['ball']

200.0

In [68]:
df['one']['ball']=220

In [69]:
df

one    two
apple   100.0  111.0
ball    220.0  222.0
cerill    NaN  333.0
clock   300.0    NaN
dancy     NaN  444.0

In [70]:
df['three']=df['one']*df['two']
df

one    two    three
apple   100.0  111.0  11100.0
ball    220.0  222.0  48840.0
cerill    NaN  333.0      NaN
clock   300.0    NaN      NaN
dancy     NaN  444.0      NaN

In [71]:
df.insert(1,'copy_of_one',df['one'])
df

one  copy_of_one    two    three
apple   100.0        100.0  111.0  11100.0
ball    220.0        220.0  222.0  48840.0
cerill    NaN          NaN  333.0      NaN
clock   300.0        300.0    NaN      NaN
dancy     NaN          NaN  444.0      NaN

In [72]:
df['flag']=df['two']>80
df

one  copy_of_one    two    three   flag
apple   100.0        100.0  111.0  11100.0   True
ball    220.0        220.0  222.0  48840.0   True
cerill    NaN          NaN  333.0      NaN   True
clock   300.0        300.0    NaN      NaN  False
dancy     NaN          NaN  444.0      NaN   True

In [73]:
df['flag']

apple      True
ball       True
cerill     True
clock     False
dancy      True
Name: flag, dtype: bool

In [75]:
import os
os.chdir('D:\dataset\ml-25m')

In [76]:
movies=pd.read_csv('movies.csv')

In [77]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [78]:
ratings=pd.read_csv('ratings.csv')
ratings.head()

userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [79]:
tags=pd.read_csv('ratings.csv')
ratings.head()

userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [80]:
movies.shape

(62423, 3)

In [81]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62423 entries, 0 to 62422
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   movieId  62423 non-null  int64 
 1   title    62423 non-null  object
 2   genres   62423 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB


In [82]:
movies.describe()

movieId
count   62423.000000
mean   122220.387646
std     63264.744844
min         1.000000
25%     82146.500000
50%    138022.000000
75%    173222.000000
max    209171.000000

In [83]:
ratings.describe()

userId       movieId        rating     timestamp
count  2.500010e+07  2.500010e+07  2.500010e+07  2.500010e+07
mean   8.118928e+04  2.138798e+04  3.533854e+00  1.215601e+09
std    4.679172e+04  3.919886e+04  1.060744e+00  2.268758e+08
min    1.000000e+00  1.000000e+00  5.000000e-01  7.896520e+08
25%    4.051000e+04  1.196000e+03  3.000000e+00  1.011747e+09
50%    8.091400e+04  2.947000e+03  3.500000e+00  1.198868e+09
75%    1.215570e+05  8.623000e+03  4.000000e+00  1.447205e+09
max    1.625410e+05  2.091710e+05  5.000000e+00  1.574328e+09

In [84]:
ratings['rating'].describe()

count    2.500010e+07
mean     3.533854e+00
std      1.060744e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [86]:
ratings['rating'].mean()

3.533854451353085

In [87]:
ratings['rating'].count()

25000095

In [88]:
ratings["rating"].std()

1.0607439610179747

In [89]:
movies.isnull().any()

movieId    False
title      False
genres     False
dtype: bool

In [90]:
movies[['title','genres']].head(20)

title  \
0                        Toy Story (1995)   
1                          Jumanji (1995)   
2                 Grumpier Old Men (1995)   
3                Waiting to Exhale (1995)   
4      Father of the Bride Part II (1995)   
5                             Heat (1995)   
6                          Sabrina (1995)   
7                     Tom and Huck (1995)   
8                     Sudden Death (1995)   
9                        GoldenEye (1995)   
10         American President, The (1995)   
11     Dracula: Dead and Loving It (1995)   
12                           Balto (1995)   
13                           Nixon (1995)   
14                Cutthroat Island (1995)   
15                          Casino (1995)   
16           Sense and Sensibility (1995)   
17                      Four Rooms (1995)   
18  Ace Ventura: When Nature Calls (1995)   
19                     Money Train (1995)   

                                         genres  
0   Adventure|Animation|Children|Comedy|Fantasy  
1                    Adventure|Children|Fantasy  
2                                Comedy|Romance  
3                          Comedy|Drama|Romance  
4                                        Comedy  
5                         Action|Crime|Thriller  
6                                Comedy|Romance  
7                            Adventure|Children  
8                                        Action  
9                     Action|Adventure|Thriller  
10                         Comedy|Drama|Romance  
11                                Comedy|Horror  
12                 Adventure|Animation|Children  
13                                        Drama  
14                     Action|Adventure|Romance  
15                                  Crime|Drama  
16                                Drama|Romance  
17                                       Comedy  
18                                       Comedy  
19           Action|Comedy|Crime|Drama|Thriller

In [91]:
is_highly_rated=ratings["rating"]>=4.0

In [92]:
ratings[is_highly_rated]

userId  movieId  rating   timestamp
0              1      296     5.0  1147880044
2              1      307     5.0  1147868828
3              1      665     5.0  1147878820
5              1     1088     4.0  1147868495
8              1     1237     5.0  1147868839
...          ...      ...     ...         ...
25000088  162541    41566     4.0  1240952749
25000089  162541    45517     4.5  1240953353
25000090  162541    50872     4.5  1240953372
25000093  162541    58559     4.0  1240953434
25000094  162541    63876     5.0  1240952515

[12452811 rows x 4 columns]

In [94]:
avg_rating = ratings[['movieId','rating']].groupby('movieId').mean()
avg_rating.head()

rating
movieId          
1        3.893708
2        3.251527
3        3.142028
4        2.853547
5        3.058434

In [95]:
movie_count = ratings[['movieId','rating']].groupby('movieId').mean()
movie_count.head()

rating
movieId          
1        3.893708
2        3.251527
3        3.142028
4        2.853547
5        3.058434

In [96]:
tags.head()

userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [97]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [98]:
t=movies.merge(tags,on='movieId',how='inner')
t.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating   timestamp  
0       2     3.5  1141415820  
1       3     4.0  1439472215  
2       4     3.0  1573944252  
3       5     4.0   858625949  
4       8     4.0   890492517

In [99]:
t=movies.merge(tags,on='movieId',how='left')
t.head()

movieId             title                                       genres  \
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
1        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
2        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
3        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   
4        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy   

   userId  rating     timestamp  
0     2.0     3.5  1.141416e+09  
1     3.0     4.0  1.439472e+09  
2     4.0     3.0  1.573944e+09  
3     5.0     4.0  8.586259e+08  
4     8.0     4.0  8.904925e+08

In [100]:
avg_ratings =ratings.groupby('movieId').mean()
avg_ratings.head()

userId    rating     timestamp
movieId                                      
1        81294.564728  3.893708  1.153152e+09
2        81358.542554  3.251527  1.122310e+09
3        81343.694934  3.142028  9.806023e+08
4        81266.193024  2.853547  9.424605e+08
5        81002.872460  3.058434  1.004723e+09

In [101]:
box_office = movies.merge(avg_ratings,on='movieId',how='inner')
box_office.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres        userId    rating  \
0  Adventure|Animation|Children|Comedy|Fantasy  81294.564728  3.893708   
1                   Adventure|Children|Fantasy  81358.542554  3.251527   
2                               Comedy|Romance  81343.694934  3.142028   
3                         Comedy|Drama|Romance  81266.193024  2.853547   
4                                       Comedy  81002.872460  3.058434   

      timestamp  
0  1.153152e+09  
1  1.122310e+09  
2  9.806023e+08  
3  9.424605e+08  
4  1.004723e+09